# ~/.config/starship.toml
"$schema" = 'https://starship.rs/config-schema.json'

# ===== Theme & Layout =====
add_newline = false
palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
base = "#1e1e2e"
surface0 = "#313244"

# ===== Prompt Format =====
format = """
$directory$git_branch$git_status$nodejs$python$rust
$character
"""

# ===== Modules =====
[directory]
style = "bold lavender"
truncation_length = 3
truncate_to_repo = true
read_only = " "

[git_branch]
symbol = " "
style = "mauve"
format = "[$symbol$branch]($style) "

[git_status]
style = "red"
format = '([\[$all_status$ahead_behind\]]($style)) '

[nodejs]
symbol = " "
style = "green"
format = "[$symbol($version )]($style)"

[python]
symbol = " "
style = "yellow"
format = "[$symbol($version )]($style)"

[rust]
symbol = " "
style = "red"
format = "[$symbol($version )]($style)"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold yellow)"
